# -*- coding: latin-1 -*-
#!/usr/bin/env python

import mynimbus
import time
import sys

print("Nimbus master start!!")
nimbus = mynimbus.NimbusMaster()
print("initialisation...")
nimbus.nimbus_init()
print("initialisation completed!")
print("Set all Gauge to 0")
nimbus.set_gauge_value(0, 0)
time.sleep(0.5)	
nimbus.set_gauge_value(1, 0)
time.sleep(0.5)
nimbus.set_gauge_value(2, 0)
time.sleep(0.5)
nimbus.set_gauge_value(3, 0)
time.sleep(4)
print("Set first gauge to 40, 60, 30 0 and 100")
nimbus.set_gauge_value(0, 40)
time.sleep(2)
nimbus.set_gauge_value(0, 60)
time.sleep(2)
nimbus.set_gauge_value(0, 30)
time.sleep(2)
nimbus.set_gauge_value(0, 0)
time.sleep(2)
nimbus.set_gauge_value(0, 100)
print("Write text on all display")
nimbus.display_text(0, "Test")
nimbus.display_text(1, "Jeedom")
nimbus.display_text(2, "Zelda")
nimbus.display_text(3, "Working")
print("play with gauges")
nimbus.set_gauge_value(0, 25)
time.sleep(0.5)
nimbus.set_gauge_value(1, 50)
time.sleep(0.5)
nimbus.set_gauge_value(2, 75)
time.sleep(0.5)
nimbus.set_gauge_value(3, 100)
time.sleep(3)
print("return to 0 all")
nimbus.set_gauge_value(0, 0)
time.sleep(0.5)
nimbus.set_gauge_value(1, 0)
time.sleep(0.5)
nimbus.set_gauge_value(2, 0)
time.sleep(0.5)
nimbus.set_gauge_value(3, 0)
