# -*- coding: latin-1 -*-
#!/usr/bin/env python

import mynimbus
import time
import sys

print("Nimbus master start!!")
nimbus = mynimbus.NimbusMaster()
print("initialisation...")
nimbus.nimbus_init()
print("initialisation completed!")
print("Set all Gauge to 0")
nimbus.setGaugeValue(0, 0)
time.sleep(0.5)	
nimbus.setGaugeValue(1, 0)
time.sleep(0.5)
nimbus.setGaugeValue(2, 0)
time.sleep(0.5)
nimbus.setGaugeValue(3, 0)
time.sleep(4)
print("Set first gauge to 40, 60, 30 0 and 100")
nimbus.setGaugeValue(0, 40)
time.sleep(2)
nimbus.setGaugeValue(0, 60)
time.sleep(2)
nimbus.setGaugeValue(0, 30)
time.sleep(2)
nimbus.setGaugeValue(0, 0)
time.sleep(2)
nimbus.setGaugeValue(0, 100)
print("Write text on all display")
nimbus.printText(0, "Test")
nimbus.printText(1, "Jeedom")
nimbus.printText(2, "Zelda")
nimbus.printText(3, "Working")
print("play with gauges")
nimbus.setGaugeValue(0, 25)
time.sleep(0.5)
nimbus.setGaugeValue(1, 50)
time.sleep(0.5)
nimbus.setGaugeValue(2, 75)
time.sleep(0.5)
nimbus.setGaugeValue(3, 100)
time.sleep(3)
print("return to 0 all")
nimbus.setGaugeValue(0, 0)
time.sleep(0.5)
nimbus.setGaugeValue(1, 0)
time.sleep(0.5)
nimbus.setGaugeValue(2, 0)
time.sleep(0.5)
nimbus.setGaugeValue(3, 0)
